x-development-volumes: &development-volumes
  volumes:
    - ./src:/workspace/app/src/
    - ./pyproject.toml:/workspace/app/pyproject.toml
    - ./uv.lock:/workspace/app/uv.lock
    - ./.env.docker.example:/workspace/app/.env

services:
  app:
    build:
      context: .
      dockerfile: deploy/docker/dev/Dockerfile
    ports:
      - "8000:8000"
      - "3006:3006"
    tty: true
    environment:
      SAQ_USE_SERVER_LIFESPAN: "false"
    command: litestar run --reload --host 0.0.0.0 --port 8000
    restart: always
    <<: *development-volumes
  # migrator:
  #   build:
  #     context: .
  #     dockerfile: deploy/docker/dev/Dockerfile
  #   command: litestar database upgrade --no-prompt
  #   restart: "no"
  #   <<: *development-volumes
  #   env_file:
  #     - .env.docker.example
  #   depends_on:
  #     db:
  #       condition: service_healthy
